version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  go_api:
    build: "../backend"
    environment:
      GOPATH: "/go"
      CODER_KEY: ${CODER_KEY}
      CONN_STR: "host=db port=5432 user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"
    command: /bin/sh -c "$TESTING_COMMAND"
    depends_on:
      - db
